view/app-jarvis.js

#12  Auto send the message when send voice is detected.

Auto send added for voice search

---

view/app-jarvis.js
view/components/main.html

#12 Now the user can either say **start Jarvis** way or click on the microphone to start recording.
The working is explained in the video. To watch the video [click here.](https://drive.google.com/file/d/1OzQEh4x4ENuVgLkbgDeLAOe7pI-spGoA/view?usp=sharing)

improvements in the speech to text feature

---

service/controllers/messages.go
view/app-jarvis.js
view/components/main.html
view/css/main.css

This forms the first major feature request, the support for **Google search through Jarvis**.
**explanatory video**
https://drive.google.com/file/d/1QomAKN1ZamJ29nOMRSJTa83GjqfoGOpu/view

Output view google

---

view/app-jarvis.js

Added the feature of sending the message on pressing the enter key.

Send the message on pressing enter key

---

view/app-jarvis.js

#18 fixed the bug, now the first letter is displayed in the message bar.

fixed the first letter error

---

view/css/main.css
view/index.html

sidebar widened

---

view/app-jarvis.js
view/css/main.css

Removed the all-time listening and detection on **start jarvis** feature. And changed the location of listening to the top of the page.

Removed the auto-detection feature

---

service/controllers/messages.go

Added the yahoo search support.
A test search is being displayed in the video. To watch the video [click here.](https://drive.google.com/file/d/1uqgqjgu9tgECqHXvAVFPMvIpaqgRSF6E/view)

added yahoo support

---

service/controllers/messages.go

Added the bing search support. #24
A test search is being displayed in the video. To watch the video [click here.](https://drive.google.com/file/d/1z2tdIzDdkshSa3dh9jDCcja1QABRD_2L/view)

added bing search support

---

view/app-jarvis.js
view/components/main.html
view/css/main.css

UI of google, yahoo, bing search engines changed

---

service/controllers/messages.go
service/controllers/subprocessHandler.go
view/app-jarvis.js
view/css/main.css

#10 The youtube search has been added in this PR. Now the user can make youtube search using Personal Assistant, the syntax of search is **youtube <message>**.
#27 And also the auto scroll to the end of the page is been added.
The features are better explained in the video. To watch the video [click here.](https://drive.google.com/file/d/1HsSqY0d1eQBcXNGdpkaEek1D4IWD2BXy/view)

Added the youtube search and autoscroll feature 

---

.travis.yml
INSTALL.md
service/controllers/messages_test.go

Broader test cases for ***google, yahoo, bing, youtube, images, weather***

Newer tests

---

view/app-jarvis.js
view/components/main.html

Fixes: #67 
Changes made:
- Empty messages are no longer allowed.
- `Type a message` was made placeholder text instead of plain text in input field.
- Removed alert for trying to send empty messages as it is cumbersome and doesn't look professional.
[video of chat screen after changes](https://drive.google.com/file/d/1yYXbGUpyRikf5mTkmEvMfXZaJG4DnER6/view)

Fixed empty message bug

---

service/controllers/check_service.go
service/controllers/messages.go
view/components/main.html

Fixes: #70 
Detailed list of changes made:
- added `check_service.go` file under `controllers` folder. The function `Connected()` in the file, checks for Internet Connectivity and returns a boolean value based on the result.
- modified `messages.go` file to display query results only when there is Internet Connection. When there is no Internet Connection, a proper error message is displayed. `General conversation remains unaffected whatever be the status of Internet Connectivity`.
- modified `main.html` file under `view/components` to display the error message.
[Link to video which shows chat application after changes](https://drive.google.com/file/d/1pyk4rB5tqq0QFF2Fl67tV5YznYkfAgr9/view)

Feature displays error message when there is no Internet Connnection

---

service/controllers/messages.go

#62 making the search requests more user friendly.
https://drive.google.com/file/d/1T1Vaxq12zLBC4YVyeWJZG5SIhBuYk4Fd/view

making search request user friendly

---

.gitignore
.travis.yml
service/controllers/messages.go
service/controllers/set_reminder.go
service/messages/health.go
service/utils/service.go
view/app-jarvis.js
view/components/main.html

Fixes: #92 
The following improvements were made:
- Pretty printed the output of `medicine <med-name>` command.
- Added functionality so that the command works even when the first character of the `med-name` is in lower-case.
- Displayed proper error message when the command is executed without Internet connectivity.
[Video showcasing changes](https://drive.google.com/file/d/18UU7-Dy2_iV0cbcGjX69evWHkLChHMqj/view)

fix: Improve health support view and functionality

---

service/controllers/messages.go

Added a priority list to check for the input and perform the action according to the priority, i.e, if a user has an input ```google weather Bhubaneswar Odisha bing```, it will return the weather conditions ignoring the Google and Bing search as the weather is higher in the priority list.
The priority list in descending order is set as:
<i>images, image, video, videos, watch, youtube, symptoms, medicine, weather, meaning, google, yahoo, bing, search</i>
Some other tests of this priority list are shown in the [video.](https://drive.google.com/file/d/1PjVl4vas-_yONmev2IpdicP-XvdIMXnN/view)

added priority list

---

view/.eslintrc.json
view/app-jarvis.js
view/components/sidebar.html
view/css/main.css

Fixes: #85 
***Utilities Hub*** in the sidebar has been updated with the **help** information, controlled by angular, and jquery.
[Explanatory Video](https://drive.google.com/file/d/1sTqYHw_JVi4OlcR3t9ued2LEiWHUbIB4/view)

sidebar UI update

---

service/controllers/messages.go
view/css/main.css

Fixed the bugs related to the links in the Yahoo and Bing search. And minor changes in UI, i.e. decreasing the height of div of every query in search request.

fixed minor bug and minor changes in UI

---

service/controllers/set_reminder.go
view/app-jarvis.js

Fixes: #107 
The following changes were made:
- A cookie was made for each reminder when it is created. They are also saved to the reminder database.
- When the user set time is up for the reminder, the cookie for the reminder expires. This is checked at regular intervals and proper alerts for the expired reminders are generated.
[video showcasing changes made](https://drive.google.com/file/d/1Jzeg3hD05O1pDHS68AvZ-biKs5SIAsB7/view)

fix: added support for alerts/notifications in the set reminder feature

---

service/controllers/messages.go
service/debug.log
service/services/herokuhost/docker.go
service/subprocesses/deploy_heroku.js
service/subprocesses/fetchdata_query.js
service/subprocesses/health_medicine.js
service/subprocesses/health_symptoms.js
tests/debug.log
tests/subs.js

***Major feature update!***
Completely automates the server deployment process at heroku containers.
*Currently, very few organizations like **Kubernetes support**auto deployment facilities.*
This PR makes Jarvis one of the select!
[Explanatory video](https://drive.google.com/file/d/1BhINUp4eWfxfbvabv69K4zQtVNRbIOTV/view)

support for Autodeployment heroku

---

service/controllers/messages.go
view/app-jarvis.js
view/components/main.html
view/css/main.css

Added extra information i.e. Description with the title and link in google, bing, yahoo and youtube search.
**_Some example view of google and youtube are_**

Added description for google, yahoo, bing and youtube

---

service/config.json
service/config/index.go
service/controllers/common.go
service/controllers/messages.go
service/maintut.go

Added priority strings and user agents to config

---

README.md

---
This PR solves issue #168 
The PR contains the updated README.md for the Repository **Jarvis-personal-assistant**.
It contains a new section **Achievements**

Added Achievements section

---

service/controllers/messages.go

This PR solves issue #153
Scraps meaning of a word with golang

Added meaning scraping using golang

---

service/controllers/messages.go
view/desktop/app/templates/components/weather-view.html
view/web/app-jarvis.js
view/web/components/main.html

This PR solves issue #152 
Scrapes weather information with golang

Added weather scraping with golang

---

view/desktop/app/assets/css/main.css
view/desktop/app/scripts/index.js
view/desktop/app/templates/components/email-view.html
view/desktop/app/templates/components/response-routes.html

---
This PR solves issue #
In this PR, the email feature is implemented in Jarvis-Desktop.
[Explanatory Video](https://drive.google.com/file/d/1_kaI2JWp4PSXTtJTbJYy69aMf5tQYVed/view)

Added email feature for desktop app

---

service/controllers/messages.go
service/go.sum
service/messages/health.go
service/scrapper/common.go

---
This PR is for issue #151 
Added medicine scrapping with golang

Added medicine scrapping with golang

---

README.md

previous commit:-
new commit:-
This PR solves issue #149 
**Files Added/Updated**
Added Postman Documentation Link to README.md
@muskankhedia and @Harkishen-Singh Please review and let me know if any changes to be made

Updated README.md with Postman doc link

---

README.md

This PR solves issue #149 
Postman documentation link added to the README.md.

Postman doc update

---

service/messages/health.go

This PR solves issue #151 
Add symptoms scrapping with golang

Added symptoms scrapping with golang

---

service/controllers/messages.go

This PR solves issue #150 
Scrapes images with golang

Added image scrapping with golang

---

INSTALL.md

This PR solves issue #198
Update `install.md` file

Updated install.md file

---

README.md

Added the link for the revamped service using NodeJS.

added NodeJS service link

---

src/service/handlers/messages.js

This PR solves issue #210 
Added meaning scrapping with node.js

Added meaning scrapping

---

go.mod
go.sum
service/controllers/ast.go
service/controllers/controllers.go

This PR solves issue #138 
Added yahoo scrapping with golang

Added yahoo scrapping with golang

---

src/service/handlers/messages.js

This PR solves issue #209 
Added yahoo scrapping

Added yahoo scrapping

---

src/service/handlers/messages.js

This PR solves issue #211 
Added bing scrapping

Added bing scrapping

---

src/service/handlers/messages.js

This PR solves issue #213 
Added weather scrapping

Added weather scrapping
